/**
 * @file post.js
 * @brief Fetches a post's markdown file, renders it with marked.js,
 *        and builds the table of contents.
 *
 * @details Loaded on every static post page generated by generate-sites.py.
 * The markdown filename is passed via the data-filename attribute on this
 * script tag, set at build time, so no data.json fetch is needed at runtime.
 *
 * The script tag injected by generate-sites.py looks like:
 * @code
 * <script src="js/post.js" data-filename="1-riscv-env-setup.md"></script>
 * @endcode
 */

/**
 * @brief Builds and injects the table of contents into #toc-content.
 *
 * @details Queries all h1 and h2 elements inside #post-content, assigns
 * stable anchor IDs to any that lack one, then builds a nested <ul>
 * mirroring the heading hierarchy. Each entry is an anchor link to its
 * corresponding heading. Renders a "No sections" placeholder if no
 * headings are found.
 *
 * Must be called after markdown has been injected into #post-content
 * so the headings are present in the DOM.
 *
 * @returns {void}
 */
function renderTOC() {
    const content = document.getElementById('post-content');
    const headings = content.querySelectorAll('h1, h2');
    const tocEl = document.getElementById('toc-content');

    if (headings.length === 0) {
        tocEl.innerHTML = '<p style="font-size:0.9rem;color:#999;">No sections</p>';
        return;
    }

    // Assign stable anchor IDs to any headings that don't already have one
    let idx = 0;
    headings.forEach(heading => {
        if (!heading.id) {
            idx++;
            heading.id = `heading-${idx}`;
        }
    });

    let html = '<ul>';
    let currentLevel = 1;
    let openLists = [1]; // Stack tracking currently open <ul> nesting levels

    headings.forEach(heading => {
        const level = parseInt(heading.tagName[1]); // Numeric level: 1 or 2
        const text = heading.textContent;
        const id = heading.id;

        if (level > currentLevel) {
            // Heading is deeper — open nested <ul> levels until we reach it
            while (currentLevel < level) {
                html += '<ul>';
                openLists.push(level);
                currentLevel++;
            }
        } else if (level < currentLevel) {
            // Heading is shallower — close open <ul> levels until we reach it
            while (currentLevel > level) {
                html += '</ul>';
                openLists.pop();
                currentLevel--;
            }
        }

        html += `<li><a href="#${id}">${text}</a></li>`;
    });

    // Close any <ul> levels still open after the last heading
    while (openLists.length > 1) {
        html += '</ul>';
        openLists.pop();
    }

    html += '</ul>';
    tocEl.innerHTML = html;
}


(function () {

    /**
     * @brief Entry point — runs after the DOM is ready.
     *
     * @details Reads the markdown filename from this script tag's
     * data-filename attribute, fetches the file from /notes/posts/,
     * strips the leading h1 (already rendered in the page header),
     * renders via marked.js, then calls renderTOC() from notes-utils.js.
     *
     * @returns {Promise<void>}
     */
    document.addEventListener('DOMContentLoaded', async function () {
        const scriptTag = document.querySelector('script[src*="post.js"]');
        if (!scriptTag) {
            console.error('post.js: could not locate own script tag');
            return;
        }

        const filename = scriptTag.dataset.filename;
        if (!filename) {
            console.error('post.js: data-filename attribute is missing');
            return;
        }

        const contentEl = document.getElementById('post-content');

        try {
            const response = await fetch(`/notes/posts/${filename}`);
            if (!response.ok) throw new Error(`HTTP ${response.status}`);

            let markdown = await response.text();

            // Strip the leading h1 — it's already rendered as the page title
            markdown = markdown.replace(/^# .+\n\n/, '');

            // Render markdown to HTML and inject into the DOM
            contentEl.innerHTML = marked.parse(markdown);

            // TOC must be built after markdown is in the DOM so headings exist
            renderTOC();

        } catch (err) {
            console.error('post.js: failed to load markdown:', err);
            contentEl.innerHTML = '<p>Error loading content. Please try refreshing.</p>';
        }
    });

}());